- hosts: all
  become: yes

  tasks:
    - pause:
        seconds: 30

    - name: install system updates for centos systems
      yum: name=* state=present update_cache=yes

    - name: install packages
      yum:
        name:
          - "curl"
          - "python3-pip"
        state: present

    - name: Make python3 the default python
      shell: "update-alternatives --install /usr/bin/python python /usr/bin/python3 1"

    - name: Make pip3 the default pip
      shell: "update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1"

    - name: install awsmfa
      pip:
        name:
          - awsmfa==0.2.9
        executable: pip3
