- hosts: all
  become: yes

  tasks:
    - pause:
        seconds: 30

    - name: install system updates for centos systems
      yum: name=* state=present update_cache=yes

    - name: install packages
      yum:
        name:
          - "curl"
          - "jq"
          - "python3-pip"
        state: present

    # - name: Make python3 the default python
    #   alternatives:
    #     name: python
    #     link: /usr/bin/python
    #     path: /usr/bin/python3

    # - name: Make pip3 the default pip
    #   alternatives:
    #     name: pip
    #     link: /usr/bin/pip
    #     path: /usr/bin/pip3

    - name: install awsmfa
      pip:
        name:
          - awsmfa==0.2.9
        executable: pip3
